huggingface/optimum-graphcore

optimum/graphcore/ipu_configuration.py

Before to get a pretrained ipu_config you had to specify the json file directly:
```
IPUConfig.from_pretrained("/path/to/config/ipu_config.json")
```
Model hub doesn't let you do this and it's not the behaviour of `from_pretrained` for other configs etc.
Now we can just do
```
IPUConfig.from_pretrained("/path/to/config")
```

Fixed bug to get ipu_config.json from_pretrained path

---

tests/test_trainer.py

`require_datasets` has been removed from `transformers`: see https://github.com/huggingface/transformers/pull/14795

Remove `require_datasets` from testing utility

---

optimum/graphcore/modeling_utils.py
optimum/graphcore/models/bert/modeling_bert.py
optimum/graphcore/models/roberta/modeling_roberta.py
optimum/graphcore/models/vit/modeling_vit.py

There's a bug when running BERT and RoBERTa fine-tuning models where after training is finished and you attempt to compile the inference model you get a tracing error in poptorch:
```
First diverging operator:
Node diff:
- %qa_outputs : __torch__.poptorch.ops.___torch_mangle_628.Linear = prim::GetAttr[name="qa_outputs"](%self.1)
?                                                      ^ -
+ %qa_outputs : __torch__.poptorch.ops.___torch_mangle_842.Linear = prim::GetAttr[name="qa_outputs"](%self.1)
?                                                      ^^
```
This was root-caused to us not removing the `outline_attributes` hooks in the `deparallelize` method for these models.
I have fixed this and also done some refactoring of RoBERTa and BERT models to remove repeated code.

Hook removal bugfix

---

examples/image-classification/README.md

- Remove unsupported parameter that breaks example

Fix image classification example

---

optimum/graphcore/modeling_utils.py
optimum/graphcore/models/bart/modeling_bart.py
optimum/graphcore/models/bert/modeling_bert.py
optimum/graphcore/models/roberta/modeling_roberta.py
optimum/graphcore/models/t5/modeling_t5.py
optimum/graphcore/models/vit/modeling_vit.py

Currently, the `IPUConfig` dict is merged into the `model.config` attribute. This is bad because when saving the model and its configuration, the IPU config content is saved in the model configuration at the same time. 
To avoid that, an `ipu_config` attribute needs to be added to pipelined models. It's already be taken care of with the class methods from `PipelineMixin`, and for the case in which a pipeline object is instantiated from the class constructor, the user should get an error when trying to parallelize the model if the attribute was not set beforehand.
We could also add an optional `ipu_config` argument to the parallelize method to allow the user to provide this config directly instead of doing:
```python
pipelined_model.ipu_config = IPUConfig.from_pretrained(....) …
```

Model ipu config attribute

---

optimum/graphcore/ipu_configuration.py

Change the allowed pod types to pods: 4, 8, 16, 32, 64.
We don't support 128 and 256 yet because they require poddist/MPI to run.

Update the allowed pod_types

---

.github/workflows/test-examples.yml
.github/workflows/test-general.yml
examples/image-classification/run_image_classification.py
examples/language-modeling/run_mlm.py
examples/multiple-choice/run_swag.py
examples/question-answering/run_qa.py
examples/summarization/run_summarization.py
examples/text-classification/run_glue.py
examples/text-classification/run_xnli.py
examples/token-classification/run_ner.py
examples/translation/run_translation.py
optimum/graphcore/ipu_configuration.py
optimum/graphcore/trainer.py
setup.py
tests/create_diff_file_for_example.py
tests/examples/run_glue.txt
tests/examples/run_image_classification.txt
tests/examples/run_mlm.txt
tests/examples/run_ner.txt
tests/examples/run_qa.txt
tests/examples/run_summarization.txt
tests/examples/run_swag.txt
tests/examples/run_translation.txt
tests/examples/run_xnli.txt
tests/test_examples.py
tests/test_examples_match_transformers.py

It provides a test checking that the optimum version of the examples is matching the transformers one.
To do that the following is done for each example script:
1. We have a "diff" file located under `tests/examples/[name of the example script].txt`, this file acts as a reference of the differences the two files should have (Trainer vs IPUTrainer, IPUConfig stuff and so on)
2. A copy of the transformers repo is downloaded and from it the "today" difference between the transformers version and the version in optimum is computed.
3. We check that this up-to-date difference matches the reference diff file.
To create the reference diff file, a tool is provided under `tests/create_diff_file_for_example.py`:
```
python tests/create_diff_file_for_example.py \
--transformers …
```

Test and tool to check that transformers and optimum examples match

---

examples/language-modeling/README.md

Updates README in [optimum-graphcore/examples/language-modeling/](https://github.com/huggingface/optimum-graphcore/tree/main/examples/language-modeling) to include BERT-large commands.
Checkpoints produced with this commands have been uploaded to [Graphcore/bert-large-uncased](https://huggingface.co/Graphcore/bert-large-uncased). The final loss after phase 2 was 1.2 and the SQuAD fine-tuning scores were EM 84.87 and F1 91.14 (reference is 84.1 and 90.9 resp. from Devlin et al. 2018)

Add BERT-large config to language modelling README

---

README.md
examples/image-classification/requirements.txt
examples/language-modeling/requirements.txt
examples/multiple-choice/requirements.txt
examples/multiple-choice/run_swag.py
examples/question-answering/requirements.txt
examples/summarization/requirements.txt
examples/summarization/run_summarization.py
examples/text-classification/requirements.txt
examples/token-classification/requirements.txt
examples/translation/requirements.txt
tests/examples/run_summarization.txt
tests/examples/run_swag.txt

This synchronizes the examples with their transformers counterparts, and adds the transformers package as a requirement to install from sources for each example.
The current issue is that optimum-graphcore requires the stable transformers package, but the examples often require installing from sources because they can us the latest changes. This was causing issues (#71), as users can end up with an "old" version of transformers when installing optimum-graphcore, making the example scripts fail.
There are multiple ways of solving this:
1. Stop checking for the latest transformers version in the examples. This can work, but since we try to match and synchronize the examples between the two libraries, it can be bug-prone.
2. Synchronizing the examples with the latest transformers release …

Examples sync

---

optimum/graphcore/ipu_configuration.py
optimum/graphcore/trainer.py

Examples where there are no labels provided in the evalulation phase (e.g. question answering) don't output a loss. The evalulation loop in the trainer was performing operations on this loss without checking if it was None.

Check if loss is none in evaluation loop

---

optimum/graphcore/trainer.py

`preprocess_logits_for_metrics` was possibly accidentally removed in https://github.com/huggingface/optimum-graphcore/commit/7cadee9f29f0aabcff17d2d33e3423370c172504 . This breaks the `run_mlm` example. Added it back.

Added back preprocess_logits_for_metrics to evaluation loop

---

README.md
examples/image-classification/requirements.txt
examples/image-classification/run_image_classification.py
examples/language-modeling/requirements.txt
examples/language-modeling/run_mlm.py
examples/multiple-choice/requirements.txt
examples/multiple-choice/run_swag.py
examples/question-answering/requirements.txt
examples/question-answering/run_qa.py
examples/question-answering/run_vqa.py
examples/summarization/requirements.txt
examples/summarization/run_summarization.py
examples/text-classification/requirements.txt
examples/text-classification/run_glue.py
examples/text-classification/run_xnli.py
examples/token-classification/requirements.txt
examples/token-classification/run_ner.py
examples/translation/requirements.txt
examples/translation/run_translation.py
tests/examples/run_glue.txt
tests/examples/run_image_classification.txt
tests/examples/run_mlm.txt
tests/examples/run_ner.txt
tests/examples/run_qa.txt
tests/examples/run_summarization.txt
tests/examples/run_swag.txt
tests/examples/run_translation.txt
tests/examples/run_xnli.txt
tests/test_examples_match_transformers.py

Main branch of transformers doesn't support Python 3.6 anymore. The examples all require source install transformers so they were broken by this. This fixes them until we can find a solution.

Fixing the transformers version to 0.4.18

---

optimum/graphcore/modeling_utils.py

Fixes the case when the type of `outputs` in `recomputation_checkpoint` is a `Tensor` instead of a Tuple. Needed for the convnet models.

Fixed recomputation checkpoint to handle Tensor types

---

optimum/graphcore/trainer.py

While saving the checkpoint, get the random number generator state before `deparallelize()` and reload it after `parallelize()`, so that checkpointing won't alter the random state and we could have reproducibility no matter what the frequency of checkpointing is.

Reload rng_state when checkpointing

---

optimum/graphcore/trainer.py

- Fixes the way speed metrics are computed for the training loop, before the number of samples was computed as follows:
```
num_samples = number of examples in the dataset x number of epochs
```
But this can over-evaluate the speed metric if the last batch is being dropped, and the batch size very big. Instead, we do now:
```
num_samples = math.ceil(args.num_train_epochs * num_update_steps_per_epoch) x total_train_batch_size
```
This might under-evaluate the speed if the last batch is mostly empty, but solves our issue of over-evaluating when dropping the last batch.
For evaluation / prediction, we always use the number of examples actually seen as the number of samples, not sure why it was not the case in the original Trainer.

Fix num samples for speed metrics

---

tests/test_examples.py

Runs examples from text_examples.py in their own virtualenvs. 
This should fix the nfs issue we are seeing with the test_examples CI when installing the requirements.
Adapted from https://github.com/huggingface/optimum-graphcore/pull/174

Make test examples tests use individual venvs

---

optimum/graphcore/trainer.py
tests/test_trainer.py

Disabled the LAMB update of bias parameters in the model. Bias parameters will be instead updated with AdamW. We've found experimentally that this helps mitigate underflow of bias variables in training. This improves stability of BERT pretraining.

Modify LAMB to disable LAMB updates on bias parameters

---

README.md
docs/source/_toctree.yml
docs/source/add_support_for_new_model.mdx
docs/source/index.mdx
docs/source/ipu_config.mdx
docs/source/quickstart.mdx
docs/source/trainer.mdx
optimum/graphcore/ipu_configuration.py
optimum/graphcore/modeling_utils.py
optimum/graphcore/models/convnext/modeling_convnext.py
optimum/graphcore/trainer.py
optimum/graphcore/training_args.py
tests/test_examples.py
tests/test_trainer.py

Updates and completes the `optimum-graphcore` documentation

Documentation

---

examples/audio-classification/requirements.txt

It uses `scikit-learn` rather than `sklearn` in a `requirements.txt` file.
scikit-learn is the actual package name, using `sklearn` in requirement files will stop working December 1st 2022. For more details, see https://github.com/scikit-learn/sklearn-pypi-package.
I checked the small issue box since it seems to apply best.

Use correct package name for scikit-learn in requirements

---

optimum/graphcore/ipu_configuration.py
optimum/graphcore/models/convnext/modeling_convnext.py

`poptorch.autocasting` not needed now we have dispatch tracing. Also will be removed completely in SDK3.1.
* Remove the deprecated and now unused autocasting ipu options
* Update comment on casting in modelin

Remove deprecated and unused autocast IPU option 

---

optimum/graphcore/ipu_configuration.py

* Half partials option is True in every single config, but the default `IPUConfig` object sets it to False by default.
* Set the default to True always.

Set enable half partials by default to True

---

notebooks/audio_classification.ipynb
notebooks/external_model.ipynb
notebooks/image_classification.ipynb
notebooks/introduction_to_optimum_graphcore.ipynb
notebooks/language_modeling.ipynb
notebooks/language_modelling_from_scratch.ipynb
notebooks/multiple_choice.ipynb
notebooks/question_answering.ipynb
notebooks/stable_diffusion/image_to_image.ipynb
notebooks/stable_diffusion/inpainting.ipynb
notebooks/stable_diffusion/text_to_image.ipynb
notebooks/summarization.ipynb
notebooks/text_classification.ipynb
notebooks/token_classification.ipynb
notebooks/translation.ipynb
notebooks/wav2vec2/wav2vec2-fine-tuning-checkpoint.ipynb
notebooks/wav2vec2/wav2vec2-inference-checkpoint.ipynb

Change 
- Each notebook to have its own poplar executable cache directory. This is needed as a workaround to prevent long .popef file loading times over cloud networks, to ensure fast compilation times.

Notebook-specific cache dirs

---

notebooks/stable_diffusion/image_to_image.ipynb
notebooks/stable_diffusion/text_to_image.ipynb

The stable diffusion image_to_image and text_to_image notebooks use the same poplar executable, so this PR makes them use the same cache to prevent uploading a duplicate file

text2img and img2img use the same cache

---

notebooks/wav2vec2/wav2vec2-inference-checkpoint.ipynb

Update the Wav2vec2 - inference notebook to use the poplar exe cache directory

wav2vec2 inference to use cachedir

---

README.md
notebooks/image_classification.ipynb

`pip install optimum[graphcore]` is installing the wrong version due to pip's dependency solver doing the wrong thing.
Changing to `pip install optimum-graphcore` installs the newest version.

Update install instructions

---

notebooks/sentiment_analysis.ipynb

We add more explicit "detachFromDevice()" calls to free up IPU resources so models in upcoming cells have IPUs to attach to.

detach from IPUs to free resources

---

notebooks/question_answering.ipynb

This PR removes a markdown cell that references GPU and TPU

remove markdown text referencing gpu

---

optimum/graphcore/models/distilbert/modeling_distilbert.py
optimum/graphcore/models/roberta/modeling_roberta.py

* In training mode for MLM models we don't want to return the logits for performance. 
* Distilbert and Roberta were only checking for `if labels is None`, but this meant that in evaluation the training path was being taken. Fix this by checking instead for `if self.training`.

Fix training mode outputs for roberta and distilbert mlm models

---

optimum/graphcore/models/convnext/modeling_convnext.py

* Removes the custom layernorm used in convnext that correctly handled mixed precision. This fix is now in upstream transformers since 4.23 so we remove it from here.

Remove the custom layernorm for convnext

---

optimum/graphcore/trainer.py
tests/test_examples.py

Changes:
1. Increase learning rate for token classification tests from 1e-5 to 1e-4 to get a previously failing test to pass. 
2. Replaces incorrect usage of `training_args.gradient_accumulation_steps` with `ipu_config.gradient_accumulation_steps`, for example when logging training information. 
Tests:
Ran the token classification tests, all 6 tests passed.

Tokenclassification testfixes

---

tests/test_examples.py

Contains fixes to examples test failures:
- Increasing default learning rate from 1e-5 to 1e-4
- Reducing eval score threshold for `groupbert_swag`
- Reducing learning rate for hubert audio classification
Test:
Running `test_examples.py` in pytest - all 30 tests pass.

test-examples: set default learning rate 1e-4

---

optimum/graphcore/generation_utils.py
optimum/graphcore/ipu_configuration.py
optimum/graphcore/pipelines/__init__.py

Current text generation returns all the logits back from IPU to host. However we only need the logits from the token to be generated. This wraps the model to return only what is necessary to improve the IO performance of the text generation.

Efficient decoder text generation wrapper

---

.github/workflows/test-examples.yml
setup.py
tests/test_examples.py

- Prevents the `venv`s  created for each example from clashing
- Uses a `FileLock` to stop concurrent `pip install`s of `optimum-graphcore`
- Add `POPTORCH_WAIT_FOR_IPU=1` to `test-examples.yml`, this allows:
- Multiple examples to compile concurrently
- Maximum IPU utilisation because the IPUs won't be idle while waiting for the next example to compile
- Increase the number of workers in CI to 4

Speed up examples CI

---

examples/speech-recognition/run_inference_ctc.py
optimum/graphcore/ipu_configuration.py
tests/pipelines/test_pipelines_automatic_speech_recognition.py

If the user were to parallelise a model themselves we make them provide `layers_per_ipu` and `ipus_per_replica`. However, `ipus_per_replica` is always just `len(layers_per_ipu)`. So I have made that the default behaviour. You can still provide it explicitly to override this if you need to.

Infer `ipus_per_replica` from `layers_per_ipu`

---

notebooks/external_model.ipynb
optimum/graphcore/ipu_configuration.py
optimum/graphcore/modeling_utils.py
optimum/graphcore/models/bart/modeling_bart.py
optimum/graphcore/models/bert/modeling_bert.py
optimum/graphcore/models/convnext/modeling_convnext.py
optimum/graphcore/models/deberta/modeling_deberta.py
optimum/graphcore/models/distilbert/modeling_distilbert.py
optimum/graphcore/models/gpt2/modeling_gpt2.py
optimum/graphcore/models/groupbert/modeling_groupbert.py
optimum/graphcore/models/hubert/modeling_hubert.py
optimum/graphcore/models/roberta/modeling_roberta.py
optimum/graphcore/models/t5/modeling_t5.py
optimum/graphcore/models/vit/modeling_vit.py
optimum/graphcore/models/wav2vec2/modeling_wav2vec2.py
tests/test_ipu_configuration.py
tests/test_trainer.py

Changes 
- `layers_per_ipu` to support wildcards (-1). Default value changed from [1] to [-1]. With this change, the `get_layer_ipu` method will use `ipus_per_replica` to fill in the `layers_per_ipu` if the wildcard is used. 
- If `ipus_per_replica` is 1, `layers_per_ipu` is ignored, and all layers are placed on IPU0. If `ipus_per_replica` > 1 and `layers_per_ipu` uses default value [-1] (or [-1] * `ipus_per_replica`), then the layers are evenly split over `ipus_per_replica` IPUs. 
- `layers_per_ipu` can support a combination of integers and wildcards e.g `[1, 1, -1, -1] will put 1 layer each on IPU0 and IPU1, and split the remaining layers evenly between IPU2 and IPU3. If there are an odd number of layers, the extra layer is placed on the last wildcard IPU. 
- Updated the docstring in …

Layers per ipu improvements

---

optimum/graphcore/ipu_configuration.py

If you try and load a very large model (in my case it was T5-XL), then you run into the following error from protobuf
```
onnx.ModelProto exceeded maximum protobuf size of 2GB
```
This PR adds `opts._Popart.set("saveInitializersToFile", NamedTemporaryFile().name)` which allows this error to be circumvented.

Add PopART option that enables the use of models with weights exceeding ~2GB

---

optimum/graphcore/modeling_utils.py
tests/test_ipu_configuration.py

Now correctly splits cases where `layers_per_ipu` has 0s in it. Examples:
```
ipu_config = IPUConfig(layers_per_ipu=[1, 2, 3, 0, 5, 6, 7, 8]) -> [1, 2, 3, 0] / [5, 6, 7, 8]
ipu_config = IPUConfig(layers_per_ipu=[0, 6, 0, 6]) -> [0, 6] / [0, 6]
ipu_config = IPUConfig(layers_per_ipu=[3, 0, 3, 0, 0, 7]) -> [3, 0, 3, 0] / [0, 7]
```

Fix encoder-decoder splitting for cases where ipus have 0 layers

---

optimum/graphcore/generation_utils.py

This would fail if `POPLAR_ENGINE_OPTIONS` was used for purposes other than profiling. This PR fixes that.

Fix when `POPLAR_ENGINE_OPTIONS` not for profiling

---

optimum/graphcore/trainer.py

if the user does not provide an optimizer to the trainer class, `self.optimizer=None` with `compile only` mode. This is okay for `Trainer.train()` since it makes the call to `self.create_optimizer()`, which instantiates an optimizer if one does not exist. This PR ensures that an optimizer is instantiated even in compile only mode. 

Instantiate optimizer in compile only mode

---

notebooks/stable_diffusion/image_to_image.ipynb
notebooks/stable_diffusion/inpainting.ipynb
notebooks/stable_diffusion/text_to_image.ipynb
notebooks/stable_diffusion/text_to_image_sd2.ipynb
optimum/graphcore/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_mixin.py
setup.py

Main upstream change was the refactoring of CrossAttention to use interchangeable AttentionProcessors.

Bump diffusers to 0.12.1

---

optimum/graphcore/modeling_utils.py

The default behaviour of `nn.Embedding.from_pretrained` is to freeze the constructed embedding weights. This may not be what the user intends to do.  This PR overrides the default value and allows the user to optionally change the behaviour (for example in `pipelined_model_cls.deparallelize()`)

SerializedEmbedding: override default freeze=True on deserialization

---

optimum/graphcore/models/t5/modeling_t5.py

- Clamps `inf` values in hidden state tensors to stabilise fp16 training

T5 revert fp16 clamping removal

---

optimum/graphcore/trainer_seq2seq.py

- unwrap poplar executor buffers before compiling an inference model for generation that has persistent buffers. Otherwise will raise an error stating that a persistent buffer does not have storage

Fix IPUSeq2SeqTrainer for models that have persistent buffers

---

optimum/graphcore/trainer.py

Fixes double parallelize issue introduced by #308

Remove extra `parallelize` from `Trainer.__init__`

---

.github/workflows/test-examples.yml
.github/workflows/test-pipelines.yml

Stops `mprof run` from hiding `pytest` failures

Add `--exit-code` to `mprof run` calls

---

.github/workflows/build_pr_documentation.yml
.github/workflows/check_code_quality.yml
.github/workflows/test-examples.yml
.github/workflows/test-general.yml
.github/workflows/test-pipelines.yml

Should remove warnings in jobs caused by outdated version of Node.js used in `actions/checkout@v2` and `actions/setup-python@v2`

Update `actions/*` to fix Node.js warnings

---

optimum/graphcore/generation_utils.py
optimum/graphcore/models/bart/modeling_bart.py
optimum/graphcore/models/whisper/modeling_whisper.py

POC using buffers to store the encoder hidden states in the decoder wrapper.
The current implementation copies all the weights and buffers every time the encoder is ran, so isn't efficient yet.

Use buffers to cache the encoder hidden states in decoder wrapper

---

optimum/graphcore/pipelines/__init__.py
optimum/graphcore/pipelines/fill_mask.py
tests/pipelines/test_pipelines_fill_mask.py

Fixes failing pipeline tests coming from index error in `fill-mask` pipeline
To validate:
```
RUN_SLOW=true pytest -k BartForConditionalGeneration tests/pipelines/test_pipelines_fill_mask.py -v
```

Only `parallelize(for_generation=True)` if pipeline task is in `SUPPORTED_GENERATION_TASKS`

---

tests/pipelines/test_pipelines_common.py

Fixes failing pipeline test coming from denormals in particular T5 layer.
To validate:
```
RUN_SLOW=true pytest -k test_load_default_pipelines_pt tests/pipelines/test_pipelines_common.py -v
```

Skip equal check for denormals in known T5 layer

---

docs/source/add_support_for_new_model.mdx
docs/source/diffusers.mdx
docs/source/ipu_config.mdx
docs/source/pipelines.mdx
docs/source/quickstart.mdx
docs/source/trainer.mdx

The links to API references that are auto-generated do not have the correct base URL. This PR manually adds links to the API references. 
Example of autogenerated link: https://huggingface.co/docs/optimum.graphcore/main/en/add_support_for_new_model#optimum.graphcore.modeling_utils.PipelineMixin.parallelize
Actual (correct) link: https://huggingface.co/docs/optimum/graphcore/add_support_for_new_model#optimum.graphcore.modeling_utils.PipelineMixin.parallelize

Fixing links to API references

---

optimum/graphcore/modeling_utils.py
tests/test_modeling_utils.py

Fixes bug in `SerializedEmbedding` where it is assumed that the `padding_idx` will be on the 0th embedding split

Add `padding_idx` to appropriate embedding split

---

examples/speech-recognition/run_whisper_pipeline.py
optimum/graphcore/ipu_configuration.py
optimum/graphcore/pipelines/__init__.py
optimum/graphcore/pipelines/automatic_speech_recognition.py

This PR makes it possible to use the HF pipeline for Whisper on the IPU.

Add IPU support for HF pipelines to Whisper 

---

optimum/graphcore/generation/utils.py
tests/generation/test_framework_agnostic.py
tests/generation/test_generation_utils.py
tests/generation/test_utils.py
tests/utils.py

- update generation tests structure to mirror transformers 4.29.2
- update generation strategies in optimum/graphcore/generation/utils.py to support multiple eos token to mirror transformers 4.29.2
- add destroy method to mirror poptorch_model.destroy()

Enable generation tests

---

optimum/graphcore/models/whisper/modeling_whisper.py

Allows the user to specify which IPU the decoder projection resides on using `serialized_projection_splits_per_ipu`.
Also requires modifications to the IPUConfig in order to compile correctly, but these are still WIP so I won't post here.

Add support for `whisper-small` fine-tuning

---

optimum/graphcore/modeling_utils.py

- Support output channels matmul serialization mode.
- Sets this as the new default to match SerializedLinear

SplitProjection layer: Add output channels serialization mode

---

notebooks/text_embeddings_models/text-embeddings-on-ipu.ipynb

Add back the commented `optimum-graphcore` source install in the notebook - now changes to source have landed.

Add back source optimum graphcore install in embeddings notebook

---

notebooks/image_classification.ipynb
notebooks/introduction_to_optimum_graphcore.ipynb
notebooks/multiple_choice.ipynb
notebooks/name-entity-extraction.ipynb
notebooks/packed_bert/packedBERT_multi_label_text_classification.ipynb
notebooks/packed_bert/packedBERT_question_answering.ipynb
notebooks/packed_bert/packedBERT_single_label_text_classification.ipynb
notebooks/question_answering.ipynb
notebooks/sentiment_analysis.ipynb
notebooks/stable_diffusion/image_to_image.ipynb
notebooks/stable_diffusion/text_to_image.ipynb
notebooks/summarization.ipynb
notebooks/text_classification.ipynb
notebooks/token_classification.ipynb
notebooks/translation.ipynb
notebooks/wav2vec2/wav2vec2-fine-tuning-checkpoint.ipynb
notebooks/wav2vec2/wav2vec2-inference-checkpoint.ipynb

This PR makes the titles of many notebooks consistent with their entries on the [IPU-powered Jupyter Notebooks](https://www.graphcore.ai/ipu-jupyter-notebooks) webpage. This makes it easier for a user to know that the link from the web page is taking them to the correct notebook.
The change is being made to the title to conform with the notebook titling convention described in the [Guidelines for Writing a Notebook](https://github.com/graphcore/examples/blob/master/utils/templates/notebook_guidelines.md#notebook-title).

Make notebook titles consistent

---

optimum/graphcore/models/bart/modeling_bart.py

Enable quantization for BART
