examples/image-classification/README.md, examples/image-classification/requirements.txt, examples/image-classification/run_image_classification.py, optimum/graphcore/models/vit/__init__.py, optimum/graphcore/models/vit/modeling_vit.py
* Added ViT model and the `image_classification` script in examples.
* Included example in readme for fine-tuning ViT on cifar10
=> Added ViT for image classification

examples/image-classification/README.md, examples/image-classification/requirements.txt, examples/image-classification/run_image_classification_on_local_data.py
- Add script to train on local image folder
- Update README for new script
- Update requirements.txt
This was tested with the latest source install (https://github.com/huggingface/optimum-graphcore/commit/d8b082ab341678ff2380eb15377a5ceea9c7c7f6).
=> Update image classification example

examples/question-answering/utils_qa.py
* Harder check for IndexErrors in QA scripts
* Copy of https://github.com/huggingface/transformers/commit/d0b5ed110aa034f21de3a1b4c043b44a7dc59c41
=> Harder check for IndexErrors in QA scripts

examples/text-classification/README.md
- Add note on correct batch size for some tasks
- These values have been correctly tested
This is a fix for https://github.com/huggingface/optimum-graphcore/issues/35
=> Update text classification example

optimum/graphcore/models/bert/modeling_bert.py
=> Fix bug in BERT checkpointing

examples/question-answering/README.md, examples/question-answering/run_qa.py, examples/question-answering/run_vqa.py, optimum/graphcore/__init__.py, optimum/graphcore/models/lxmert/__init__.py, optimum/graphcore/models/lxmert/modeling_lxmert.py, optimum/graphcore/models/t5/modeling_t5.py, tests/test_pipelined_models.py, tests/utils.py
1. Still need to refactor the datasets and change the code accordingly.
2. Convergence runs on whole datasets are yet to be done.
=> [WIP] Add LXMERT for visual question answering

.github/workflows/test-examples.yml, .github/workflows/test-general.yml, examples/language-modeling/run_mlm.py, examples/multiple-choice/run_swag.py, examples/question-answering/run_qa.py, examples/summarization/run_summarization.py, examples/text-classification/run_glue.py, examples/text-classification/run_xnli.py, examples/token-classification/run_ner.py, examples/translation/run_translation.py, optimum/graphcore/ipu_configuration.py, optimum/graphcore/trainer.py, optimum/graphcore/training_args.py, setup.py, tests/examples/run_glue.txt, tests/examples/run_mlm.txt, tests/examples/run_ner.txt, tests/examples/run_qa.txt, tests/examples/run_summarization.txt, tests/examples/run_swag.txt, tests/examples/run_translation.txt, tests/examples/run_xnli.txt, tests/ipu_config_trainer_test.json, tests/test_trainer.py
- Clean and remove unsused code in the Trainer
- The `IPUTrainer` can now accept optimizers in the init and those will be converted to `poptorch.DataLoader`
- "New" tests
- Multiple bugs fixed
Fixes: #67
=> Trainer cleanup

examples/image-classification/run_image_classification.py, examples/language-modeling/run_mlm.py, examples/multiple-choice/run_swag.py, examples/question-answering/run_qa.py, examples/question-answering/run_vqa.py, examples/summarization/run_summarization.py, examples/text-classification/run_glue.py, examples/text-classification/run_xnli.py, examples/token-classification/run_ner.py, examples/translation/run_translation.py, optimum/graphcore/training_args.py, tests/examples/run_glue.txt, tests/examples/run_image_classification.txt, tests/examples/run_mlm.txt, tests/examples/run_ner.txt, tests/examples/run_qa.txt, tests/examples/run_summarization.txt, tests/examples/run_swag.txt, tests/examples/run_translation.txt, tests/examples/run_xnli.txt
Added updates to the example scripts from transformers fixing the unit tests.
"Add use_auth to load_datasets for private datasets"
https://github.com/huggingface/transformers/commit/24a85cca61fda92b9376fe45da1dcb10c8853066
=> Synced examples with latest transformers

examples/image-classification/run_image_classification.py, examples/language-modeling/run_mlm.py, examples/language-modeling/run_pretraining.py, examples/multiple-choice/run_swag.py, examples/question-answering/run_qa.py, examples/question-answering/run_vqa.py, examples/summarization/run_summarization.py, examples/text-classification/run_glue.py, examples/text-classification/run_xnli.py, examples/token-classification/run_ner.py, examples/translation/run_translation.py, optimum/graphcore/__init__.py, optimum/graphcore/models/t5/modeling_t5.py, optimum/graphcore/utils/__init__.py, optimum/graphcore/version.py, tests/examples/run_glue.txt, tests/examples/run_image_classification.txt, tests/examples/run_mlm.txt, tests/examples/run_ner.txt, tests/examples/run_qa.txt, tests/examples/run_summarization.txt, tests/examples/run_swag.txt, tests/examples/run_translation.txt, tests/examples/run_xnli.txt
This adds a version check to all the examples. This should prevent and notice users trying out the examples from a pypi installation that they should install from sources.
=> Add check_min_version to examples

optimum/graphcore/generation_utils.py
Some changes to improve text generation so that it would be easier to integrate the run_generation.py task.
=> Improve generation

examples/translation/run_translation.py, tests/examples/run_translation.txt
* Fixes a missing arg error in the `run_translation.py` example
=> Use seq2seq data collator always in the translation example

optimum/graphcore/models/bart/modeling_bart.py, optimum/graphcore/models/bert/modeling_bert.py, optimum/graphcore/models/roberta/modeling_roberta.py, optimum/graphcore/models/t5/modeling_t5.py, tests/test_pipelined_models.py
1. Fix models' `deparallelize`.
2. Improve the unittests that tests `parallelize` and `deparallelize`.
=> Fix deparallelize

examples/language-modeling/README.md, examples/language-modeling/run_clm.py, examples/language-modeling/run_mlm.py, optimum/graphcore/__init__.py, optimum/graphcore/ipu_configuration.py, optimum/graphcore/models/__init__.py, optimum/graphcore/models/bert/__init__.py, optimum/graphcore/models/gpt2/__init__.py, optimum/graphcore/models/gpt2/modeling_gpt2.py, optimum/graphcore/models/gpt2/optimized_gpt2_attn.py, optimum/graphcore/models/roberta/__init__.py, tests/examples/run_clm.txt, tests/examples/run_glue.txt, tests/examples/run_mlm.txt, tests/examples/run_ner.txt, tests/examples/run_xnli.txt, tests/test_examples.py, tests/test_pipelined_models.py, tests/utils.py
1. There is no pre-trained multilingual GPT2 available, but GPT2 still support XNLI fine-tuning.
2. A bug was recently fixed in SDK 2.5.0, so the GPT2 model will not successfully compile with the current default SDK 2.4.0. This PR should probably be merged after we have SDK 2.5.0 as our default.
=> Added GPT2 model

examples/token-classification/run_ner.py, optimum/graphcore/modeling_utils.py, optimum/graphcore/models/__init__.py, optimum/graphcore/models/deberta/__init__.py, optimum/graphcore/models/deberta/modeling_deberta.py, optimum/graphcore/trainer.py, tests/examples/run_ner.txt, tests/utils.py
Waiting on next poplar SDK to land to main
=> Add DeBERTa

optimum/graphcore/trainer.py
=> Make compilation happen before speed metric starts for inference

optimum/graphcore/models/bart/modeling_bart.py, optimum/graphcore/models/t5/modeling_t5.py, optimum/graphcore/trainer_seq2seq.py, optimum/graphcore/training_args_seq2seq.py, tests/generation/test_generation_utils.py
This PR adds an error message when the user wants to use `--predict_with_generate` since it is not well supported for now.
=> Error message when trying to use generate

optimum/graphcore/__init__.py, optimum/graphcore/trainer.py, tests/test_trainer.py
=> Fixes speed metric issue when resuming from checkpoint

optimum/graphcore/trainer.py
Previously `TrainingArguments.compile_only` didn't do anything.
Now with `compile_only` enabled the program will exit completely without running the training/evalulation loops.
Fixes #110
=> Enabled compile_only option

optimum/graphcore/models/vit/modeling_vit.py
=> Use last_ipu variable instead of a fixed ipu id for ViT

README.md
=> Add Poplar SDK setup guide to README

notebooks/squad_preprocessing.py
=> Style fix for notebooks/squad_preprocessing.py

examples/summarization/README.md, examples/translation/README.md, examples/translation/run_translation.py, tests/examples/run_translation.txt
=> [WIP] Fix translation padding

examples/summarization/README.md, examples/translation/README.md
=> Modify Bart commands

optimum/graphcore/__init__.py
=> Add PipelinedBartForSequenceClassification to __init__.py

tests/test_examples.py, tests/test_pipelined_models.py, tests/utils.py
With this PR, it is possible to specify task-specific IPU configurations for `test_examples`.
=> Can specify task specific IPU configs in test_example

optimum/graphcore/models/wav2vec2/ipu_layer_drop.py
=> Fix layerdrop for Wav2Vec2

examples/speech-recognition/run_speech_recognition_ctc.py, optimum/graphcore/models/wav2vec2/ipu_gumbel_vector_quantizer.py, optimum/graphcore/models/wav2vec2/modeling_wav2vec2.py, tests/examples/run_speech_recognition_ctc.txt, tests/test_pipelined_models.py
Fixes tests/test_pipelined_models.py::PipelinedModelsTester for Wav2Vec2 models
- [N] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [N] Did you make sure to update the documentation with your changes?
- [Y] Did you write any new necessary tests?
=> Fix test_pretrained_and_pipelined_models_match for Wav2Vec2

examples/image-classification/run_image_classification.py, tests/examples/run_image_classification.txt
- Image classification: casts inputs to fp16 in the dataset when training in fp16
=> Fix fp16 issue for image classification

optimum/graphcore/models/wav2vec2/ipu_layer_drop.py
1. Remove Wav2Vec2 padding
2. Modify IPU layerdrop
=> Remove  Wav2Vec2 padding

examples/audio-classification/run_audio_classification.py, optimum/graphcore/models/hubert/ipu_layer_drop.py, optimum/graphcore/models/hubert/modeling_hubert.py, tests/examples/run_audio_classification.txt
=> Layerdrop for HuBERT

examples/language-modeling/run_clm.py, tests/examples/run_clm.txt
=> Remove CLM's config_overrides limit

optimum/graphcore/trainer.py
This PR allows users to specify a data collator that is applied only to the evaluation dataset. This allows the application of data augmentation only to training or evaluation datasets
=> eval data collator

examples/language-modeling/README.md, optimum/graphcore/ipu_configuration.py, optimum/graphcore/training_args.py, tests/test_trainer.py
=> Enable --auto-loss-scaling flag in Optimum

.github/workflows/build_pr_documentation.yml, Makefile, docs/Dockerfile, setup.py
This PR fixes two bugs related to documentation generation:
- In the Docker image associated to the container building the doc, `hf-doc-builder` is installed from PyPI using `pip install .[quality]`. An install from source is needed to get [this fix](https://github.com/huggingface/doc-builder/pull/270).
- In the Docker image associated to the container building the doc, the repo is cloned but it points by default to the `main` branch. Thus, the doc generated for each PR is actually the doc of the `main` branch. This is fixed by checking out the commit associated to the PR when cloning the repo in the `Dockerfile`. See [here](https://github.com/huggingface/optimum-habana/pull/78) for more explanations.
=> Fix doc build bugs

examples/speech-pretraining/run_pretraining.py
=> Fix Wav2Vec2 async rebatched

.github/workflows/build_pr_documentation.yml, Makefile, docs/Dockerfile, docs/source/index.mdx
The PR doc generation would fail if the PR comes from a fork. This PR fixes that by extracting the clone URL in the GH workflow and providing it to the Dockerfile.
It also adds a default clone URL to the Makefile so that the main documentation of Optimum (the parent package) can be generated without any optimum-graphcore-PR clone URL.
=> Generate PR doc from forks

tests/test_examples.py
* Run each example in `test_examples.py` in a temp directory in the examples directory.
* Also set the `HF_HOME` to that examples directory. This way the datasets/caches are created and destroyed with every test case, leaving nothing behind that could cause side effects.
This should fix #172
=> Run each test-example completely with dataset in a tempdir 

examples/language-modeling/README.md
=> Update mlm command

examples/language-modeling/run_mlm.py, examples/language-modeling/run_pretraining.py, optimum/graphcore/data/data_collator.py, optimum/graphcore/models/bert/modeling_bert.py, optimum/graphcore/models/roberta/modeling_roberta.py, tests/examples/run_mlm.txt
=> Compute max_num_masked_tokens dynamically

.github/workflows/test-examples.yml, tests/test_examples.py
Each test in `tests/test_examples.py` will now use its own virtual environment.
=> Make each example use its own venv

Makefile
See https://github.com/huggingface/optimum/pull/357
=> Fix broken documentation source links

tests/test_examples.py
- Adds tests for the `audio-classification` task
- Adds test for the `speech-recognition` task
- Simplifies the existing test classes
=> Audio classification and speech recognition tests in test_examples.py

optimum/graphcore/ipu_configuration.py, optimum/graphcore/models/gpt2/modeling_gpt2.py, optimum/graphcore/trainer.py, setup.py, tests/test_trainer.py
This PR enables some tests in `test_trainer.py` that were commented because the SDK was not supporting them before.
=> test_trainer.py update

optimum/graphcore/models/distilbert/modeling_distilbert.py
=> Print seperate lines

.github/workflows/test-examples.yml, .github/workflows/test-general.yml, examples/audio-classification/run_audio_classification.py, examples/speech-pretraining/run_pretraining.py, examples/speech-recognition/run_inference_ctc.py, examples/speech-recognition/run_speech_recognition_ctc.py, examples/text-classification/run_glue.py, optimum/graphcore/ipu_configuration.py, optimum/graphcore/modeling_utils.py, optimum/graphcore/models/bart/modeling_bart.py, optimum/graphcore/models/bert/modeling_bert.py, optimum/graphcore/models/convnext/modeling_convnext.py, optimum/graphcore/models/deberta/__init__.py, optimum/graphcore/models/deberta/modeling_deberta.py, optimum/graphcore/models/distilbert/modeling_distilbert.py, optimum/graphcore/models/gpt2/modeling_gpt2.py, optimum/graphcore/models/gpt2/optimized_gpt2_attn.py, optimum/graphcore/models/hubert/ipu_layer_drop.py, optimum/graphcore/models/hubert/modeling_hubert.py, optimum/graphcore/models/lxmert/modeling_lxmert.py, optimum/graphcore/models/roberta/modeling_roberta.py, optimum/graphcore/models/t5/modeling_t5.py, optimum/graphcore/models/vit/modeling_vit.py, optimum/graphcore/models/wav2vec2/ipu_layer_drop.py, optimum/graphcore/models/wav2vec2/modeling_wav2vec2.py, optimum/graphcore/trainer.py, tests/examples/run_audio_classification.txt, tests/examples/run_glue.txt, tests/examples/run_speech_recognition_ctc.txt, tests/test_pipelined_models.py
This makes Optimum compatible with the Poplar 3.0 SDK release. 
The biggest change is that we are now using poptorch's dispatch tracer, which replaces the JIT tracer.
The main benefits of this are:
1. Better type handling - we can get rid of `poptorch.autocast`
2. Native argument and output handling. We can pass kwargs and dictionarys to the IPU models and also use dictionary outputs. 
3. Faster tracing
=> SDK3.0 Release

optimum/graphcore/models/deberta/modeling_deberta.py
* The deberta optimisations made in #183 have memory issues with NER.
* Reverting the optimisations for now.
=> Revert the Deberta attention optimisation

optimum/graphcore/trainer.py
This fixes an issue in `Trainer.save_model`, making model saving fail.
=> Fix Trainer.save_model issue

optimum/graphcore/models/gpt2/optimized_gpt2_attn.py
=> Improve GPT2 attention

notebooks/introduction_to_optimum_graphcore.ipynb, notebooks/text_classification.ipynb
- Changing text_classification.ipynb and introduction_to_optimum_graphcore.ipynb tutorials to pod4 configurations.
- Edited text to reflect changes.
- Tested locally and checking these scripts run on pod4's
=> Changing selective tutorials to pod4 configurations

docs/Dockerfile
This PR updates the base Docker image used in the documentation Dockerfile because the former one leads to an error when generating the doc: https://github.com/huggingface/optimum/actions/runs/3353000257/jobs/5568143450
=> Update Docker image in documentation Dockerfile

notebooks/external_model.ipynb, optimum/graphcore/trainer.py
* Fix bug with unwrapping when detaching/attaching tied-weight models
* Language modeling notebooks were failing when the trainer switches from train->evaluate
=> Fix bug with unwrapping when detaching/attaching tied-weight models

.github/workflows/build_pr_documentation.yml
This PR fixes the issue where the PR doc cannot be pushed to the remote server. See https://github.com/huggingface/optimum/pull/495.
=> Fix PR doc generation

notebooks/wav2vec2/wav2vec2-fine-tuning-checkpoint.ipynb
Temporary work-around to help the finetuning to succeed reliably.
=> Set seed in wav2vec finetuning notebook

docs/source/_toctree.yml
With this PR, the "Optimum Intel" section in the documentation of Optimum will be folded by default. See https://github.com/huggingface/optimum/pull/535 for more information.
=> Fold documentation by default

notebooks/stable_diffusion/text_to_image_sd2.ipynb
Add a dedicated popef folder for the sd2 notebook, similar to existing stable diffusion notebooks
=> sd2 dedicated popef folder

notebooks/sentiment_analysis.ipynb
Update the sentiment analysis notebook - RoBerta-L to split over 2 IPUs
=> sentiment analysis roberta-L 2-IPU pipeline

notebooks/sentiment_analysis.ipynb
Update the text in the sentiment analysis notebook to explain why we change the config for the Roberta-L model.
=> improve text for sentiment analysis

notebooks/sentiment_analysis.ipynb
Add notebook-specific cachedir for sentiment analysis
=> update cache dir for sentiment analysis

notebooks/sentiment_analysis.ipynb, notebooks/stable_diffusion/image_to_image.ipynb, notebooks/stable_diffusion/inpainting.ipynb, notebooks/stable_diffusion/text_to_image.ipynb, notebooks/stable_diffusion/text_to_image_sd2.ipynb, notebooks/wav2vec2/wav2vec2-inference-checkpoint.ipynb
Adds detaching of models from IPUs to notebooks. Notebooks using the IPUTrainer do not require this as detaching is handled internally.
=> Add detaching of models to notebooks

notebooks/name-entity-extraction.ipynb
Minor changes to update the NER Notebook:
- updated optimum requirements
- removed kwargs warnings from gradio
- added `launch(share=True)` to render app on PS.
=> Updated requirements and visual warnings

notebooks/sentiment_analysis.ipynb
=> Fix detaching in sentiment analysis notebook

optimum/graphcore/models/gpt2/modeling_gpt2.py, optimum/graphcore/trainer.py, tests/test_trainer.py
=> Enable commented out trainer tests now that dict inputs are supported

optimum/graphcore/pipelines/__init__.py
* Remove the recompile logic from the forward that's not working properly
* Add default truncation to the text-gen pipelines
=> Pipeline bug fixes

README.md
=> Rename sequence to text in supported models table

notebooks/packed_bert/utils/packing/dataset_creator.py
small fix for better defined error catching when passing args to dataset creator (remove the attempt to determine the task from the number of labels - this wont work most of the time anyway so better to make it a required arg)
=> Error catching fix for packed dataset creator

.github/workflows/test-general.yml, setup.py
Makes the tests run faster on the CI machine by running them in parallel. 
=> Make general tests run in parallel

.github/workflows/build_pr_documentation.yml, Makefile, docs/Dockerfile
This PR fixes the doc build which is currently broken because:
- The Docker image does not install the latest node.js version
- The name of your clone repo may not be `optimum-graphcore`, for example here: https://github.com/graphcore/optimum-graphcore-fork
=> Fix doc build

notebooks/stable_diffusion/image_to_image.ipynb, notebooks/stable_diffusion/inpainting.ipynb, notebooks/stable_diffusion/ipu_models.py, notebooks/stable_diffusion/text_to_image.ipynb, notebooks/stable_diffusion/text_to_image_sd2.ipynb
=> Enable all SD modules to run on IPU

optimum/graphcore/pipelines/text2text_generation.py
Uses `super()._sanitize_parameters()` instead of copying the function contents. 
=> Use `super()` instead of copying function contents

optimum/graphcore/models/bart/modeling_bart.py, optimum/graphcore/models/t5/modeling_t5.py
This is done for all other models. Should be done here for completeness.
=> Populate  `_hooks` for T5 and BART 

README.md, setup.py
=> Pin the optimum version requirement

README.md
Simplifies the dev install instructions so that the user can copy and paste a single block
=> More concise dev install instructions

.github/workflows/test-examples.yml, .github/workflows/test-general.yml, docs/Dockerfile, examples/audio-classification/requirements.txt, examples/image-classification/requirements.txt, examples/speech-pretraining/requirements.txt, examples/speech-recognition/requirements.txt, optimum/graphcore/modeling_utils.py, optimum/graphcore/models/bart/modeling_bart.py, optimum/graphcore/trainer.py, setup.py
Updates and fixes specific to Poplar SDK 3.2.
- Updates the package version of `torch`, `torchvision` and `torchaudio` in the requirements and setup.py files.
- Removes the work-around for detached and reattaching models that use tied-embeddings since the issue is now resolved in 3.2
=> Updates for SDK 3.2

optimum/graphcore/models/bart/modeling_bart.py, optimum/graphcore/models/t5/modeling_t5.py
Remove the work-around for rebuilding BaseModelOutput in BART and T5 because it's now fixed in SDK 3.2
=> Remove the work-around for rebuilding BaseModelOutput in BART and T5

notebooks/stable_diffusion/ipu_models.py, pyproject.toml, tests/test_trainer.py
=> Update the Python target version for black to 3.8

.github/workflows/test-pipelines.yml
=> Fix CI name for pipelines tests

notebooks/stable_diffusion/image_to_image.ipynb, notebooks/stable_diffusion/inpainting.ipynb, notebooks/stable_diffusion/requirements.txt, notebooks/stable_diffusion/text_to_image.ipynb, notebooks/stable_diffusion/text_to_image_sd2.ipynb, optimum/graphcore/diffusers/__init__.py, optimum/graphcore/diffusers/pipelines/__init__.py, optimum/graphcore/diffusers/pipelines/stable_diffusion/__init__.py, optimum/graphcore/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py, optimum/graphcore/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_img2img.py, optimum/graphcore/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_inpaint.py, optimum/graphcore/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_mixin.py, optimum/graphcore/diffusers/pipelines/stable_diffusion/safety_checker.py, setup.py
=> Move stable diffusion files into the source lib under new diffusers subfolder

.github/workflows/test-examples.yml, .github/workflows/test-general.yml, .github/workflows/test-pipelines.yml
=> Capture PopTorch error log as artifact

optimum/graphcore/models/whisper/modeling_whisper.py
Removes a large copy of the embedding weight for pipelined decoders in Whisper.
=> Move whisper decoder projection to IPU 0 since there is weight tying

optimum/graphcore/generation_utils.py, optimum/graphcore/models/whisper/modeling_whisper.py
Intended usage for Whisper:
```python
pipelined_model = pipelined_model.parallelize(
for_generation=True, use_cache=use_cache, batch_size=batch_size, max_length=448, num_beams=num_beams
)
pipelined_model.generate(input_features, use_cache=use_cache, **kwargs)
```
=> Add generic KV caching support, use it with Whisper

optimum/graphcore/generation_utils.py, optimum/graphcore/models/bart/modeling_bart.py, optimum/graphcore/models/gpt2/modeling_gpt2.py, optimum/graphcore/models/t5/modeling_t5.py, optimum/graphcore/models/whisper/modeling_whisper.py
=> move the IndexedInputLinear out of the decoder wrapper

examples/speech-pretraining/README.md, examples/speech-recognition/README.md
Adding Wav2vec2 Large pretraining and fine-tuning commands.
We had only the Base version previously.
=> Adding Wav2vec2 Large pretraining and fine-tuning

.gitignore
Stops cached executables from appearing in `git diff`
=> Add `*.popef` to `.gitignore`

optimum/graphcore/models/distilbert/modeling_distilbert.py, optimum/graphcore/models/wav2vec2/modeling_wav2vec2.py
=> Populate the _hooks for wav2vec2 and distilbert

optimum/graphcore/generation_utils.py
Small QoL fix for profile directory naming
=> Don't append `decoder` for decoder only generation

optimum/graphcore/trainer.py
=> Fix bug in trainer caused by parallelize and optimizer creation order

notebooks/summarization.ipynb, notebooks/translation.ipynb
- Enable support for prediction with generation in notebooks
=> Enable generation in notebooks that use IPUSeq2SeqTrainer

setup.py
The correct torch version is implictly already installed by `poptorch`. Removing it because it's incompatible version with systems that use Python3.9. 
=> Remove torch dependency from setup.py

optimum/graphcore/generation/logits_process.py, optimum/graphcore/generation/on_device_generation.py, optimum/graphcore/generation/utils.py
=> Add on device beam search

optimum/graphcore/ipu_configuration.py, optimum/graphcore/modeling_utils.py, optimum/graphcore/pipelines/__init__.py, pytest.ini, setup.py, tests/test_ipu_configuration.py
- Add attribute value type checking 
- Add attribute value validation
- Add validation of ipu config values
=> Add attribute validation

optimum/graphcore/ipu_configuration.py
=> Matmul proportion support float or len(List[float]) == ipus_per_replica 

notebooks/packed_bert/models/modeling_bert_packed.py, optimum/graphcore/ipu_configuration.py, optimum/graphcore/modeling_utils.py, optimum/graphcore/models/bert/modeling_bert.py, optimum/graphcore/models/convnext/modeling_convnext.py, optimum/graphcore/models/deberta/modeling_deberta.py, optimum/graphcore/models/distilbert/modeling_distilbert.py, optimum/graphcore/models/gpt2/modeling_gpt2.py, optimum/graphcore/models/groupbert/modeling_groupbert.py, optimum/graphcore/models/hubert/modeling_hubert.py, optimum/graphcore/models/roberta/modeling_roberta.py, optimum/graphcore/models/vit/modeling_vit.py, optimum/graphcore/models/wav2vec2/modeling_wav2vec2.py, optimum/graphcore/trainer.py, tests/test_ipu_configuration.py
The use of IPUConfig `ManagedAttribute`s currently involves the use of three attributes: `attribute`, `training_attribute` and `inference_attribute` (e.g. `layers_per_ipu`, `training_layers_per_ipu` and `inference_layers_per_ipu`). `attribute` is overrided internally to be a descriptor that returns `training_attribute` or `inference_attribute` depending on the `IPUConfig` mode. Since `attribute` is a descriptor, outside of the `Trainer` and `Pipeline` api, it is not guaranteed that the behaviour of the descriptor `attribute` will be consistent with the user expectation since the `IPUConfig` mode has to be set correctly.  This PR moves  `attribute` to a  descriptor `_attribute` that is handled internally, removing the need for the user to be concerned with the `IPUConfig` mode behaviour. …
=> Refactor: prefix IPUConfig `ManagedAttribute`s instead of overloading user provided attributes

optimum/graphcore/generation/attention_mixin.py, optimum/graphcore/models/whisper/modeling_whisper.py
=> Add attention serialization to the attention mixin and enable it with Whisper

optimum/graphcore/generation/logits_process.py, optimum/graphcore/generation/utils.py, optimum/graphcore/models/bart/modeling_bart.py
=> BART KV-caching + on-device

optimum/graphcore/modeling_utils.py
=> Bugfix: split matmul proportion using the mode managed attribute

notebooks/whisper-example.ipynb
There have been some updates to the notebooks template. This PR implements those updates in this notebook.
=> Minor changes to make whisper-example.ipynb consistent with template updates

optimum/graphcore/generation/utils.py
=> Fix cached_beam_idx check for non on device generation

optimum/graphcore/ipu_configuration.py, tests/test_ipu_configuration.py
=> Update ipu configuration tests

optimum/graphcore/modeling_utils.py, optimum/graphcore/models/bert/modeling_bert.py, optimum/graphcore/models/deberta/modeling_deberta.py, optimum/graphcore/models/distilbert/modeling_distilbert.py, optimum/graphcore/models/gpt2/modeling_gpt2.py, optimum/graphcore/models/groupbert/modeling_groupbert.py, optimum/graphcore/models/roberta/modeling_roberta.py
=> Refactor SerializedEmbedding to use to/from_model 

optimum/graphcore/generation/attention_mixin.py, optimum/graphcore/generation/on_device_generation.py, optimum/graphcore/generation/utils.py, optimum/graphcore/models/bart/modeling_bart.py, optimum/graphcore/models/whisper/modeling_whisper.py
Random tidy ups, doc string additions / clarifications for attention mixin and related.
=> Attn mixin improvements

notebooks/deberta-blog-notebook.ipynb
PR for a notebook demonstrating DeBERTa SQuAD and MNLI
=> Deberta notebook to accompany blog post

optimum/graphcore/models/whisper/__init__.py, optimum/graphcore/models/whisper/feature_extraction_whisper.py, optimum/graphcore/models/whisper/processing_whisper.py
=> Add a faster torch based version of the whisper feature extractor

optimum/graphcore/ipu_configuration.py, optimum/graphcore/modeling_utils.py, tests/test_ipu_configuration.py, tests/test_modeling_utils.py
- Adding the necessary IPU configuration options that will enable sharding serialized layers like `SerializedEmbedding` and `SplitLinear` across IPUs by using a pipeline configuration similar to `layers_per_ipu`. For example `[0, 0, 1, 2]` as an argument to `serialized_projection_splits_per_ipu` will result in 1 shard of a linear layer being placed on IPU2 and the last 2 shards on the last IPU.  The pipelines will also be split in a similar way for generation. For example if `layers_per_ipu=[0, 2, 2, 0]`, the corresponding encoder and decoder pipelines will be `[0, 2]` and `[2, 0]`. Similarly, `serialized_projection_layers_per_ipu` will be `[0, 0]` and `[1, 2]` for the encoder and decoder respectively. However the encoder portion `[0, 0]` is overrided with `None` as it is no longer a …
=> Support sharding serialized layers across ipus

.github/workflows/check_code_quality.yml, .github/workflows/test-general.yml
Adds concurrency checking to `check_code_quality.yml` and `test-general.yml` so that runs from outdated commits will be stopped
=> Use GitHub Actions concurrency to save time in CI

optimum/graphcore/models/bart/modeling_bart.py
Call `super()` to revert to upstream behaviour.
=> Fix BART Positional embeddings for generation without caching

tests/pipelines/test_pipelines_common.py
=> In pipeline tests, only change exception's test, not all tests

optimum/graphcore/trainer_seq2seq.py
=> Fix: reparallelize for training after generation

optimum/graphcore/models/hubert/modeling_hubert.py, optimum/graphcore/models/wav2vec2/modeling_wav2vec2.py, tests/test_examples.py
=> Change hyper-parameters to fix Hubert for CTC CI

optimum/graphcore/ipu_configuration.py
Since the replication factor can change at runtime, the choice of enabling RTS should be dynamic
=> Do not override replicated_tensor_sharding in the IPUConfig

optimum/graphcore/modeling_utils.py
=> Preserve the set padding idx in SerializedEmbedding

notebooks/flan_t5_inference.ipynb
Removes some unnecessary `print` statements
=> Flan-T5 Notebook Formatting Tweaks

optimum/graphcore/generation/attention_mixin.py, optimum/graphcore/models/whisper/modeling_whisper.py
=> Add cross KV caching

optimum/graphcore/models/whisper/feature_extraction_whisper.py
=> Fix Whisper processor torch with transformers 4.29.2 bump

notebooks/stable_diffusion/image_to_image.ipynb, notebooks/stable_diffusion/inpainting.ipynb, notebooks/stable_diffusion/text_to_image.ipynb, notebooks/stable_diffusion/text_to_image_sd2.ipynb
These notebooks had not been updated to use `n_ipu` instead of `pod_type`
=> Fix Stable Diffusion notebooks

optimum/graphcore/trainer_seq2seq.py, optimum/graphcore/training_args.py, optimum/graphcore/training_args_seq2seq.py, tests/test_trainer_seq2seq.py
Adds an integration tests for the IPUSeq2Seq trainer based on https://github.com/huggingface/transformers/blob/main/tests/trainer/test_trainer_seq2seq.py
=> Add Seq2Seq trainer test 

optimum/graphcore/generation/logits_process.py, optimum/graphcore/generation/on_device_generation.py, optimum/graphcore/generation/utils.py, tests/pipelines/test_pipelines_automatic_speech_recognition.py
=> Add support for Whisper timestamp decoding with on-device generation

optimum/graphcore/generation/logits_process.py
=> Fix IPUWhisperTimeStampLogitsProcessor for beam search

optimum/graphcore/generation/__init__.py, optimum/graphcore/generation/attention_mixin.py, optimum/graphcore/generation/utils.py, optimum/graphcore/models/whisper/modeling_whisper.py, optimum/graphcore/pipelines/__init__.py, optimum/graphcore/pipelines/automatic_speech_recognition.py
*caveat: when `use_cond_encoder=True`
=> Enable replication with on device text generation

.github/workflows/build_pr_documentation.yml, .github/workflows/delete_doc_comment.yml, .github/workflows/delete_doc_comment_trigger.yml, .github/workflows/upload_pr_documentation.yml
Doc build workflows have to be updated following https://github.com/huggingface/doc-builder/pull/379.
=> Update doc workflows

examples/speech-recognition/run_whisper_pipeline.py
=> Update whisper pipeline example for latest features

optimum/graphcore/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_mixin.py
=> Fix text encoder for SD with 4.29 bump

examples/speech-recognition/run_whisper_pipeline.py
=> Use the faster whisper feature extractor in whisper pipelines

.github/workflows/test-examples.yml
Show execution times of example tests
Output format:
```
1930.67s call     tests/test_examples.py::QuestionAnsweringExampleTester::test_run_qa_deberta                                                                                                                                                                                                                                              
1600.59s call     tests/test_examples.py::MultipleChoiceExampleTester::test_run_swag_groupbert                                                                                                                                                                                                                                             
1569.01s call     tests/test_examples.py::SummarizationExampleTester::test_run_ …
```
=> Print execution time of each example test

tests/test_examples.py
- Sets the loss scaling for the Glue task which makes training more stable for deberta.
- Enables preprocessing workers in all cases where possible to speed up the data preprocessing.
=> 3.3 Examples CI Fixes

.github/workflows/test-examples.yml, .github/workflows/test-general.yml, .github/workflows/test-pipelines.yml
=> Bump SDK version to 3.3 in the github workflows

examples/audio-classification/requirements.txt, examples/image-classification/requirements.txt, examples/speech-pretraining/requirements.txt, examples/speech-recognition/requirements.txt
Updates the torchaudio and torchvision versions in the requirements files.
=> Update examples requirements for sdk3.3

optimum/graphcore/ipu_configuration.py
=> Support C600 card

optimum/graphcore/ipu_configuration.py, optimum/graphcore/training_args.py
=> Remove deprecated pod_type argument

notebooks/stable_diffusion/stable_diffusion_space/ipu_models.py, tests/pipelines/test_pipelines_automatic_speech_recognition.py
=> Fix inference replication factor pod type removal

optimum/graphcore/generation/attention_mixin.py, optimum/graphcore/generation/utils.py, optimum/graphcore/models/t5/modeling_t5.py
=> T5 enable self-attention kv caching

tests/pipelines/test_pipelines_common.py, tests/test_examples.py, tests/test_pipelined_models.py, tests/utils.py
- support the use of IPUConfig instances in addition to strings
- support overriding *ExampleTester class attribute values when submitting tests
- provide mt5 ipu configs for summarization and translation
=> Support overriding *ExampleTester class attribute values in test_examples.py

optimum/graphcore/modeling_utils.py, optimum/graphcore/models/bart/modeling_bart.py, optimum/graphcore/models/whisper/modeling_whisper.py
=> Fix shift tokens right usage which contains slice assignment

tests/test_pipelined_models.py, tests/utils.py
=> Fix mt5 translation training ipu config 

examples/speech-recognition/run_whisper_pipeline.py, optimum/graphcore/ipu_configuration.py, optimum/graphcore/pipelines/__init__.py, optimum/graphcore/trainer.py, optimum/graphcore/trainer_seq2seq.py, tests/pipelines/test_pipelines_automatic_speech_recognition.py, tests/test_pipelined_models.py
=> Add parallelize kwargs as an IPU config entry

optimum/graphcore/models/t5/modeling_t5.py
- enable cross kv caching
- add on device generation support
- enable encoder output buffer
=> T5 enable generation optimisation

optimum/graphcore/models/whisper/modeling_whisper.py
=> Fix ipus per replica check in whisper cond encoder

notebooks/whisper_finetuning.ipynb, optimum/graphcore/generation/utils.py
=> Add notebook for whisper finetuning

optimum/graphcore/models/bart/modeling_bart.py
=> Use index select in BART positional embedding for better tile placement

optimum/graphcore/generation/utils.py
=> Change max length adaption messages to debug

notebooks/whisper_finetuning.ipynb
=> Fix finetuning whisper notebook text

notebooks/whisper_finetuning.ipynb
=> Fix finetuning whisper notebook text v2

notebooks/whisper_finetuning.ipynb, optimum/graphcore/generation/utils.py
=> Fix evaluate then train

notebooks/whisper_finetuning.ipynb
=> Use token=False in whisper nb

notebooks/text_embeddings_models/text-embeddings-on-ipu.ipynb, notebooks/text_summarization.ipynb, notebooks/whisper-quantized-example.ipynb
Adds changes made while testing on paperspace and run on gradient buttons. Notebooks tested on paperspace using pod4 and pod16.
=> Backport paperpsace changes

docs/Dockerfile
=> Update node version for doc building
